fix: CAS-100 fixed name of nftItem and nftCollections
casimir-ai/sandbox-portal pull request #32
Opened 2022-07-04 09:09 UTC by d-tsaruk

https://deip.atlassian.net/browse/CAS-29

2022-07-04 11:28 UTC, ShmidtAlex approved these changes

2022-07-04 11:28 UTC, ShmidtAlex commented on package.json
> +    "@casimir/scopes-module": "1.385.0",
Дим, а где ты проверял текущие версии модулей?

2022-07-04 12:05 UTC, d-tsaruk commented on package.json
> +    "@casimir/scopes-module": "1.385.0",
там команда есть 

<img width="675" alt="image" src="https://user-images.githubusercontent.com/45588750/177151227-f2482b96-6a35-4a7b-bd87-4f75e9ec7cad.png">

2022-07-04 16:04 UTC, elena-vlasova commented on src/modules/nftCollections/components/content/NftItemDraftsList/NftItemDraftsList.vue
> +    name: 'NftItemMetadataDraftsList',
без metadata

2022-07-04 16:04 UTC, elena-vlasova commented on src/modules/nftCollections/router/index.js
>          path: ':nftCollectionId/content/:contentId',
локализацию и роуты тоже надо поправить

2022-07-05 09:26 UTC, d-tsaruk commented on src/modules/nftCollections/components/NftCollectionForm/NftCollectionForm.vue
>        },
убрал

2022-07-05 09:27 UTC, d-tsaruk commented on src/modules/nftCollections/components/content/NftItemDraftsList/NftItemDraftsList.vue
> +    name: 'NftItemMetadataDraftsList',
поправил

2022-07-05 12:43 UTC, elena-vlasova requested changes
Не вижу изменений в ключах локализации.

Почему решил вынести компоненты из папки content?

2022-07-05 13:36 UTC, d-tsaruk commented
> Не вижу изменений в ключах локализации.
> 
> Почему решил вынести компоненты из папки content?

мы же вроде от контента уходим. переименовывать тогда над в nftItems, но тогда у нас выходит вложенность nftItems/nftItems.
поэтому подумал что лучше будет тогда вынести что бы они были на одном уровне с nftCollections и т п.

2022-07-05 13:37 UTC, d-tsaruk commented on src/modules/nftCollections/components/NftCollectionForm/NftCollectionForm.vue
> -        :nft-collection="nftCollectionMetadata"
а. упс. перепроверю

2022-07-05 13:37 UTC, d-tsaruk commented on src/modules/nftCollections/router/index.js
> +        name: 'nftCollections.nftItem.draft.create',
вроде менял, перепроверю

2022-07-07 11:56 UTC, d-tsaruk commented on src/modules/nftCollections/router/index.js
> +        name: 'nftCollections.nftItem.draft.create',
я вроде везде перепроверил, изменено.

2022-07-07 16:10 UTC, elena-vlasova submitted a review, later dismissed

2022-07-08 08:58 UTC, elena-vlasova approved these changes

2022-07-08 08:59 UTC, merged